version: '3.8'
networks: 
  ovms-bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
services:
  ovms_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    hostname: ovms-server
    ports:
      - "9000:9000"
    expose: 
      - "9000"
    networks:
      ovms-bridge:
        ipv4_address: 172.28.1.10
    command: [--port=9000, --model_name=face-detection, --model_path=/models/face-detection, --shape=auto]
    tty: 
      true

  ovms_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment: 
      SERVER_NAME: ovms-server
      GRPC_PORT: 9000
    ports:
      - "8000:8000"
    networks:
      ovms-bridge:
        ipv4_address: 172.28.1.20
    depends_on:
      - ovms_server
    links: 
      - ovms_server
    tty:
      true
